<?php

namespace Database\Seeders;

use App\Models\SaintProfile;
use Illuminate\Database\Seeder;

class SaintsAndAfricanHeritageSeeder extends Seeder
{
    public function run(): void
    {
        $saints = [
            // =========================================================================
            // 1. DIOCESAN CATHEDRAL PATRONESS & UNIVERSAL DOCTOR
            // =========================================================================
            [
                'name' => 'St. Theresa of the Child Jesus',
                'slug' => 'st-theresa-of-lisieux',
                'title_designation' => 'Doctor of the Church & Cathedral Patroness',
                'feast_day_month_day' => '10-01',
                'birth_year' => '1873',
                'death_year' => '1897',
                'country_region' => 'France (Patroness of Livingstone Cathedral)',
                'is_african_heritage' => false,
                'patronages' => ['Livingstone Diocesan Cathedral', 'Missions', 'Youth Formation', 'Florists'],
                'biography' => 'St. Thérèse of Lisieux, also known as "The Little Flower," entered the Carmel of Lisieux at age 15. She pioneered the "Little Way" of spiritual childhood—a path of doing ordinary actions with extraordinary love and total childlike abandonment to God\'s merciful love. In 1997, Pope St. John Paul II declared her a Doctor of the Universal Church. She is the beloved patroness of St. Theresa Cathedral Parish in Livingstone.',
                'virtues_exemplified' => ['Spiritual Childhood', 'Trust', 'Heroic Simplicity', 'Missionary Zeal', 'Universal Love'],
                'key_teachings_quotes' => [
                    'My vocation is love! In the heart of the Church, my Mother, I will be Love.',
                    'Miss no single opportunity of making some small sacrifice, here by a smiling look, there by a kindly word; always doing the smallest right and doing it all for love.',
                    'I will spend my heaven doing good on earth. I will let fall a shower of roses.',
                ],
                'patronage_prayer' => 'St. Theresa of the Child Jesus, beloved patroness of our Cathedral in Livingstone, obtain for our youth the grace to walk your Little Way of confidence and love. Shower your roses of blessing upon our Diocese, our families, and our Catholic youth. Amen.',
                'icon_or_image_url' => '🌹',
            ],

            // =========================================================================
            // 2. AFRICAN YOUTH PATRONS & MARTYRS OF UGANDA
            // =========================================================================
            [
                'name' => 'St. Charles Lwanga and Companions',
                'slug' => 'st-charles-lwanga',
                'title_designation' => 'Martyrs of Uganda & African Youth Patrons',
                'feast_day_month_day' => '06-03',
                'birth_year' => '1860',
                'death_year' => '1886',
                'country_region' => 'Uganda',
                'is_african_heritage' => true,
                'patronages' => ['African Catholic Youth Action', 'Uganda', 'African Youth', 'Converts'],
                'biography' => 'St. Charles Lwanga was chief of the royal pages in the court of King Mwanga II of Buganda. When persecution broke out against Christians, Charles baptized and protected young pages, strengthening their faith. On June 3, 1886, at Namugongo, Charles and twenty-one companion martyrs joyfully chose death by fire rather than renounce their Catholic faith and moral purity.',
                'virtues_exemplified' => ['Courage', 'Moral Purity', 'Youth Leadership', 'Fidelity unto Death', 'Martyrdom'],
                'key_teachings_quotes' => [
                    'A well which has much water is not easily dried up.',
                    'You are burning my body, but you cannot burn my soul. I die for the religion of Jesus Christ.',
                ],
                'patronage_prayer' => 'Holy Martyrs of Uganda, St. Charles Lwanga and your brave young companions, you stood steadfast for Jesus Christ in the face of persecution. Pray for all Catholic youth in Zambia and across Africa, that we may stand courageous in our faith and live pure, holy lives. Amen.',
                'icon_or_image_url' => '🔥',
            ],
            [
                'name' => 'St. Kizito',
                'slug' => 'st-kizito',
                'title_designation' => 'Youngest Uganda Martyr & Patron of Children',
                'feast_day_month_day' => '06-03',
                'birth_year' => '1872',
                'death_year' => '1886',
                'country_region' => 'Uganda',
                'is_african_heritage' => true,
                'patronages' => ['Children', 'Primary School Youth', 'Altar Servers', 'Uganda'],
                'biography' => 'St. Kizito was only 14 years old when he was martyred at Namugongo. Baptized by St. Charles Lwanga on the eve of their arrest, Kizito refused to renounce Christ, singing hymns of joy and forgiveness as he walked hand-in-hand with his fellow young Christians to martyrdom.',
                'virtues_exemplified' => ['Childlike Faith', 'Joy in Suffering', 'Courageous Loyalty', 'Purity of Heart'],
                'key_teachings_quotes' => [
                    'Goodbye, friends! We are on our way to Heaven.',
                    'I am a Christian and I will remain a Christian until death.',
                ],
                'patronage_prayer' => 'St. Kizito, brave child of God and martyr of Africa, inspire our young Catholic youth and altar servers with holy boldness and joy in serving Jesus Christ. Amen.',
                'icon_or_image_url' => '🌟',
            ],
            [
                'name' => 'St. Mathias Mulumba',
                'slug' => 'st-mathias-mulumba',
                'title_designation' => 'Uganda Martyr & Model of Christian Marriage',
                'feast_day_month_day' => '06-03',
                'birth_year' => '1836',
                'death_year' => '1886',
                'country_region' => 'Uganda',
                'is_african_heritage' => true,
                'patronages' => ['African Families', 'Catholic Husbands', 'Judges & Leaders', 'Uganda'],
                'biography' => 'St. Mathias Mulumba was a senior assistant chief and judge in the kingdom of Buganda. Upon converting to Catholicism, he dismissed his multiple wives with generous provision, married one woman in holy matrimony, and opened his home as a center of prayer and catechesis before dying a heroic martyr\'s death.',
                'virtues_exemplified' => ['Christian Matrimony', 'Moral Integrity', 'Righteous Leadership', 'Generosity'],
                'key_teachings_quotes' => [
                    'God will rescue me, but not in the way you think: He will take me to His kingdom.',
                ],
                'patronage_prayer' => 'St. Mathias Mulumba, pray for African husbands, fathers, and civic leaders, that they may lead their homes and communities in righteousness and Catholic faith. Amen.',
                'icon_or_image_url' => '🛡️',
            ],
            [
                'name' => 'Blessed Isidore Bakanja',
                'slug' => 'blessed-isidore-bakanja',
                'title_designation' => 'Martyr of the Brown Scapular (DR Congo)',
                'feast_day_month_day' => '08-12',
                'birth_year' => '1887',
                'death_year' => '1909',
                'country_region' => 'Democratic Republic of Congo',
                'is_african_heritage' => true,
                'patronages' => ['Catholic Laity', 'Young Workers', 'Brown Scapular Wearers', 'DR Congo'],
                'biography' => 'A young Congolese bricklayer and devout Catholic, Isidore Bakanja wore the Carmelite Brown Scapular as a badge of his devotion to Our Lady and shared the Gospel with fellow workers. Ordered by a colonial plantation manager to remove his scapular, Isidore refused. He was brutally flogged, dying months later while praying for and forgiving his killer.',
                'virtues_exemplified' => ['Forgiveness of Enemies', 'Lay Evangelization', 'Marian Devotion', 'Fortitude in Work'],
                'key_teachings_quotes' => [
                    'If you see my mother, tell her that I die because I am a Christian.',
                    'I forgive the manager with all my heart. When I am in Heaven, I will pray for him.',
                ],
                'patronage_prayer' => 'Blessed Isidore Bakanja, you bore your sufferings with peace and prayed for those who persecuted you. Help African Catholic young workers to stand unashamed of our Catholic faith in our workplaces. Amen.',
                'icon_or_image_url' => '📿',
            ],
            [
                'name' => 'Blessed Marie-Clémentine Anuarite Nengapeta',
                'slug' => 'blessed-anuarite-nengapeta',
                'title_designation' => 'Virgin Martyr & African Patroness of Purity',
                'feast_day_month_day' => '12-01',
                'birth_year' => '1939',
                'death_year' => '1964',
                'country_region' => 'Democratic Republic of Congo',
                'is_african_heritage' => true,
                'patronages' => ['African Religious Sisters', 'Young Women', 'Purity', 'DR Congo'],
                'biography' => 'A consecrated Congolese religious sister of the Holy Family, Sister Anuarite was captured during the 1964 Simba Rebellion. When a rebel colonel demanded she violate her religious vow of chastity, she firmly refused, saying "I prefer to die rather than commit sin." She was martyred while forgiving her attackers.',
                'virtues_exemplified' => ['Consecrated Chastity', 'Radical Forgiveness', 'Courage in Peril', 'Religious Fidelity'],
                'key_teachings_quotes' => [
                    'I forgive you for you know not what you are doing.',
                    'I do not want to commit sin. Kill me rather than force me to sin against God.',
                ],
                'patronage_prayer' => 'Blessed Anuarite, you preserved your consecration to Christ at the cost of your life. Intercede for young African women and girls, that they may walk in dignity, purity, and spiritual strength. Amen.',
                'icon_or_image_url' => '🌺',
            ],
            [
                'name' => 'Blessed Daudi Okelo & Blessed Jildo Irwa',
                'slug' => 'blessed-daudi-okelo-jildo-irwa',
                'title_designation' => 'Young Catechist Martyrs of Uganda',
                'feast_day_month_day' => '10-18',
                'birth_year' => '1902',
                'death_year' => '1918',
                'country_region' => 'Uganda',
                'is_african_heritage' => true,
                'patronages' => ['Catechists', 'Youth Leaders', 'Peer Evangelization', 'Northern Uganda'],
                'biography' => 'Daudi Okelo (aged 16) and Jildo Irwa (aged 12) were young Acholi Catholics who volunteered to bring the Gospel to northern Uganda. Despite warnings of armed raids, they faithfully gathered children each day to teach the catechism and pray the Rosary, and were martyred together for refusing to abandon their mission.',
                'virtues_exemplified' => ['Catechetical Zeal', 'Peer Witness', 'Courageous Missionary Spirit', 'Brotherhood in Christ'],
                'key_teachings_quotes' => [
                    'We are ready to die. We have done nothing wrong; we were only teaching the religion of God.',
                ],
                'patronage_prayer' => 'Blessed Daudi and Blessed Jildo, you gave your youth to teach the Catholic faith. Inspire our youth catechists and Sunday school animators in Livingstone Diocese with love for the Gospel. Amen.',
                'icon_or_image_url' => '📖',
            ],
            [
                'name' => 'Blessed Benedict Daswa',
                'slug' => 'blessed-benedict-daswa',
                'title_designation' => 'South African Martyr of Truth & Educator',
                'feast_day_month_day' => '02-01',
                'birth_year' => '1946',
                'death_year' => '1990',
                'country_region' => 'South Africa',
                'is_african_heritage' => true,
                'patronages' => ['African Teachers', 'Catholic Principals', 'Fathers', 'Opponents of Witchcraft'],
                'biography' => 'A devout Catholic father of eight and primary school principal in Limpopo, South Africa, Benedict Daswa refused to contribute money to hire a witchdoctor after lightning struck a village. Standing firmly on Catholic truth against superstition and witchcraft, he was ambushed and martyred by a mob while praying on his knees.',
                'virtues_exemplified' => ['Christian Truth over Superstition', 'Catholic Education', 'Family Headship', 'Peaceful Witness'],
                'key_teachings_quotes' => [
                    'My Catholic faith forbids me to take part in witchcraft or divination.',
                    'Lord, receive my spirit into Your hands.',
                ],
                'patronage_prayer' => 'Blessed Benedict Daswa, first beatified martyr of Southern Africa, grant our youth courage to reject superstition and witchcraft, anchoring our lives solely in the Power of the Cross of Jesus Christ. Amen.',
                'icon_or_image_url' => '✝️',
            ],
            [
                'name' => 'Blessed Cyprian Michael Iwene Tansi',
                'slug' => 'blessed-cyprian-michael-tansi',
                'title_designation' => 'Nigerian Cistercian Monk & Priest of Prayer',
                'feast_day_month_day' => '01-20',
                'birth_year' => '1903',
                'death_year' => '1964',
                'country_region' => 'Nigeria & Mount Saint Bernard Abbey',
                'is_african_heritage' => true,
                'patronages' => ['African Priests', 'Seminarians', 'Monastic Vocations', 'Nigeria'],
                'biography' => 'Born in Onitsha, Nigeria, Father Cyprian Tansi traveled on foot and bicycle across villages preaching the sanctity of marriage and defending the dignity of women. Later feeling called to contemplative prayer, he entered Mount Saint Bernard Abbey as a Cistercian monk, offering continuous prayer for the Church in Africa.',
                'virtues_exemplified' => ['Contemplative Prayer', 'Pastoral Zeal', 'Asceticism', 'Defense of Women'],
                'key_teachings_quotes' => [
                    'If you want to be a Christian, you must live your faith wholeheartedly, not half-heartedly.',
                ],
                'patronage_prayer' => 'Blessed Cyprian Tansi, pray for holy vocations to the priesthood and religious life in Livingstone Diocese, and teach our youth the power of silent prayer. Amen.',
                'icon_or_image_url' => '⛪',
            ],
            [
                'name' => 'St. Josephine Bakhita',
                'slug' => 'st-josephine-bakhita',
                'title_designation' => 'Virgin & Patroness of Hope',
                'feast_day_month_day' => '02-08',
                'birth_year' => '1869',
                'death_year' => '1947',
                'country_region' => 'Sudan',
                'is_african_heritage' => true,
                'patronages' => ['Sudan', 'Human Trafficking Victims', 'Survivors of Slavery', 'Forgiveness'],
                'biography' => 'Born in Darfur, Sudan, Josephine was kidnapped at age seven and sold into cruel slavery, enduring torture and scarring. Eventually brought to Italy, she encountered the Canossian Sisters and discovered the true God who loved her as His child. Declared free by Italian courts, she consecrated her life as a religious sister, spending fifty years radiating joyful humility and boundless forgiveness.',
                'virtues_exemplified' => ['Radical Forgiveness', 'Christian Hope', 'Humility', 'Joy in Christ', 'Reconciliation'],
                'key_teachings_quotes' => [
                    'If I were to meet the slave-traders who kidnapped me, I would kneel and kiss their hands, for if that had not happened, I would not be a Christian and a religious sister today.',
                    'Be good, love the Lord, pray for those who do not know Him. What a great grace it is to know God!',
                ],
                'patronage_prayer' => 'St. Josephine Bakhita, you were enslaved by humans but freed by Christ. Intercede for all victims of exploitation and human trafficking, and heal our wounds with the supernatural gift of forgiveness. St. Josephine Bakhita, pray for us. Amen.',
                'icon_or_image_url' => '🕊️',
            ],

            // =========================================================================
            // 3. AFRICAN CHURCH FATHERS, DOCTORS & DESERT MONASTICS
            // =========================================================================
            [
                'name' => 'St. Augustine of Hippo',
                'slug' => 'st-augustine-of-hippo',
                'title_designation' => 'Doctor of Grace & Bishop of Hippo',
                'feast_day_month_day' => '08-28',
                'birth_year' => '354',
                'death_year' => '430',
                'country_region' => 'Numidia (Modern Algeria), North Africa',
                'is_african_heritage' => true,
                'patronages' => ['Theologians', 'Printers', 'Seekers of Truth', 'African Church Fathers'],
                'biography' => 'Born in Tagaste, North Africa, Augustine pursued worldly philosophy and pleasure before experiencing a profound conversion in Milan through the prayers of his mother St. Monica. Returning to Africa, he was ordained Bishop of Hippo. Augustine became one of the greatest theologians in Christian history, author of "Confessions" and "The City of God," and champion of God\'s sovereign grace.',
                'virtues_exemplified' => ['Search for Truth', 'Theological Wisdom', 'Pastoral Zeal', 'Contrition', 'Love of Scripture'],
                'key_teachings_quotes' => [
                    'You have made us for yourself, O Lord, and our hearts are restless until they rest in You.',
                    'Late have I loved you, O Beauty ever ancient, ever new, late have I loved you!',
                    'To fall in love with God is the greatest romance; to seek Him the greatest adventure; to find Him, the greatest human achievement.',
                ],
                'patronage_prayer' => 'St. Augustine, great African Doctor of the Church, help our youth when our hearts are restless and searching for meaning. Guide us to find our rest and purpose in the living God and His Holy Church. Amen.',
                'icon_or_image_url' => '📜',
            ],
            [
                'name' => 'St. Monica of Hippo',
                'slug' => 'st-monica-of-hippo',
                'title_designation' => 'Patroness of Mothers & Persistent Prayer',
                'feast_day_month_day' => '08-27',
                'birth_year' => '332',
                'death_year' => '387',
                'country_region' => 'Tagaste (Modern Algeria), North Africa',
                'is_african_heritage' => true,
                'patronages' => ['Mothers', 'Difficult Marriages', 'Wayward Children', 'Conversion of Relatives'],
                'biography' => 'An African Christian mother born in modern-day Algeria, Monica prayed with relentless perseverance for over thirty years for the conversion of her pagan husband Patricius and her wayward, brilliant son Augustine. Her tears and unwavering faith were rewarded when both embraced the Catholic faith before her death.',
                'virtues_exemplified' => ['Persevering Prayer', 'Maternal Patience', 'Christian Hope', 'Gentle Forbearance'],
                'key_teachings_quotes' => [
                    'Nothing is far from God.',
                    'Lay this body anywhere and take no trouble over it; one thing only I request of you, that you remember me at the altar of the Lord wherever you may be.',
                ],
                'patronage_prayer' => 'St. Monica, loving African mother, you never gave up praying for your son Augustine. Intercede for our parents, families, and young people who have drifted from the Church. Bring them home to Christ. Amen.',
                'icon_or_image_url' => '🕯️',
            ],
            [
                'name' => 'St. Athanasius of Alexandria',
                'slug' => 'st-athanasius',
                'title_designation' => 'Doctor of the Church & Champion of Nicaea',
                'feast_day_month_day' => '05-02',
                'birth_year' => '296',
                'death_year' => '373',
                'country_region' => 'Alexandria, Egypt, North Africa',
                'is_african_heritage' => true,
                'patronages' => ['Theologians', 'Defenders of the Faith', 'Egypt', 'African Church Fathers'],
                'biography' => 'Known as "Athanasius Contra Mundum" (Athanasius against the world), this Egyptian Church Father defended the true divinity of Jesus Christ against the Arian heresy at the Council of Nicaea (325 AD). He suffered five exiles spanning seventeen years for refusing to compromise Catholic truth.',
                'virtues_exemplified' => ['Doctrinal Courage', 'Defense of Orthodoxy', 'Theological Clarity', 'Uncompromising Integrity'],
                'key_teachings_quotes' => [
                    'God became man so that man might become divine in grace.',
                    'If the world is against truth, then I am against the world.',
                ],
                'patronage_prayer' => 'St. Athanasius of Alexandria, pillar of orthodoxy and Doctor of the Church, grant our youth unwavering confidence in Jesus Christ, true God and true Man. Amen.',
                'icon_or_image_url' => '🏛️',
            ],
            [
                'name' => 'St. Cyril of Alexandria',
                'slug' => 'st-cyril-of-alexandria',
                'title_designation' => 'Doctor of the Incarnation & Defender of Theotokos',
                'feast_day_month_day' => '06-27',
                'birth_year' => '376',
                'death_year' => '444',
                'country_region' => 'Alexandria, Egypt, North Africa',
                'is_african_heritage' => true,
                'patronages' => ['Alexandria', 'Marian Theologians', 'Council Fathers', 'Egypt'],
                'biography' => 'Patriarch of Alexandria, St. Cyril was the leading theologian of the Council of Ephesus (431 AD). He courageously defended the Blessed Virgin Mary as Theotokos (Mother of God) against the Nestorian heresy, establishing the authentic Catholic teaching on the one divine Person of Jesus Christ.',
                'virtues_exemplified' => ['Marian Devotion', 'Theological Precision', 'Council Leadership', 'Defense of the Incarnation'],
                'key_teachings_quotes' => [
                    'We hail you, Mary Mother of God, venerable treasure of the whole universe, lamp that is never extinguished, crown of virginity.',
                    'Christ is one, Son, Lord, and Only-begotten.',
                ],
                'patronage_prayer' => 'St. Cyril of Alexandria, Defender of Mary the Mother of God, deepen our Catholic youth\'s love for Jesus the Word made flesh and His Holy Mother Mary. Amen.',
                'icon_or_image_url' => '👑',
            ],
            [
                'name' => 'St. Anthony the Great (Anthony of Egypt)',
                'slug' => 'st-anthony-of-egypt',
                'title_designation' => 'Father of Christian Monasticism & Desert Father',
                'feast_day_month_day' => '01-17',
                'birth_year' => '251',
                'death_year' => '356',
                'country_region' => 'Egypt, North Africa',
                'is_african_heritage' => true,
                'patronages' => ['Monastics', 'Spiritual Warriors', 'Skin Diseases', 'Egypt'],
                'biography' => 'Hearing the Gospel words "Go, sell what you have and give to the poor," Anthony gave away his large estate in Egypt and retreated into the desert. He lived in solitary prayer, overcame severe demonic temptations through the sign of the cross, and mentored thousands of hermits, earning the title "Father of All Monks."',
                'virtues_exemplified' => ['Radical Detachment', 'Solitary Prayer', 'Victory in Temptation', 'Spiritual Discernment'],
                'key_teachings_quotes' => [
                    'I no longer fear God, but I love Him, for love casts out fear.',
                    'A time is coming when men will go mad, and when they see someone who is not mad, they will attack him, saying: You are mad; you are not like us.',
                ],
                'patronage_prayer' => 'St. Anthony of the Egyptian Desert, teach our young people how to conquer the temptations of the world through silent prayer, fasting, and total love for Jesus. Amen.',
                'icon_or_image_url' => '🏜️',
            ],
            [
                'name' => 'St. Pachomius the Great',
                'slug' => 'st-pachomius-of-egypt',
                'title_designation' => 'Founder of Communal Monastic Life',
                'feast_day_month_day' => '05-09',
                'birth_year' => '292',
                'death_year' => '348',
                'country_region' => 'Upper Egypt, North Africa',
                'is_african_heritage' => true,
                'patronages' => ['Religious Communities', 'Monasteries', 'Egypt'],
                'biography' => 'Born to pagan parents in Upper Egypt, Pachomius was touched by the charity of Christians who brought food to imprisoned soldiers. After his baptism, he founded the first cenobitic (communal) monasteries along the Nile, establishing rules of shared prayer, work, and community charity that shaped all Christian religious life.',
                'virtues_exemplified' => ['Brotherly Love', 'Community Life', 'Organized Charity', 'Obedience'],
                'key_teachings_quotes' => [
                    'To help another person in faith and love is greater than raising the dead.',
                ],
                'patronage_prayer' => 'St. Pachomius, father of Christian community life, unite our Catholic youth groups in Livingstone Diocese in true brotherly and sisterly love. Amen.',
                'icon_or_image_url' => '🤝',
            ],
            [
                'name' => 'St. Moses the Black',
                'slug' => 'st-moses-the-black',
                'title_designation' => 'Desert Father of Repentance & Nonviolence',
                'feast_day_month_day' => '08-28',
                'birth_year' => '330',
                'death_year' => '405',
                'country_region' => 'Egypt & Nubia (Ethiopia/Sudan Border)',
                'is_african_heritage' => true,
                'patronages' => ['Converts from Crime', 'Peacemakers', 'Nonviolence', 'Africa'],
                'biography' => 'Formerly a notorious bandit leader in the Nile Valley, Moses sought refuge in a desert monastery in Scetis and experienced a total transformation of heart. Ordained a priest, he became renowned for his humility, spiritual counsel, and radical refusal to judge fellow sinners, ultimately laying down his life nonviolently when invaders attacked his monastery.',
                'virtues_exemplified' => ['Radical Repentance', 'Non-Judgmental Love', 'Humility', 'Peacemaking'],
                'key_teachings_quotes' => [
                    'My sins run out behind me like sand, and I do not see them, and today I have come to judge the errors of another man!',
                    'Go, sit in your cell, and your cell will teach you everything.',
                ],
                'patronage_prayer' => 'St. Moses the Black, powerful witness of God\'s transformative mercy, help youth who feel trapped in past mistakes to know that no sin is greater than God\'s divine forgiveness. Amen.',
                'icon_or_image_url' => '⚓',
            ],
            [
                'name' => 'St. Perpetua and St. Felicity',
                'slug' => 'st-perpetua-and-felicity',
                'title_designation' => 'African Martyrs of Carthage',
                'feast_day_month_day' => '03-07',
                'birth_year' => '181',
                'death_year' => '203',
                'country_region' => 'Carthage (Modern Tunisia), North Africa',
                'is_african_heritage' => true,
                'patronages' => ['Mothers', 'Expectant Women', 'Butchers', 'North African Church'],
                'biography' => 'Vibia Perpetua, a 22-year-old noble African mother with an infant child, and Felicity, a pregnant enslaved woman, were catechumens arrested in Carthage for professing Christ. Refusing to offer sacrifice to Roman gods, they stood hand-in-hand in the arena, encouraging fellow Christians before receiving the martyr\'s crown.',
                'virtues_exemplified' => ['Heroic Loyalty to Christ', 'Sisterhood in Faith', 'Maternal Sacrifice', 'Martyr\'s Joy'],
                'key_teachings_quotes' => [
                    'Stand fast in the faith, and love one another, and do not be tempted to do anything wrong because of our sufferings.',
                    'I cannot call myself by any other name than what I am: a Christian.',
                ],
                'patronage_prayer' => 'St. Perpetua and St. Felicity, noble African heroines of the faith, pray for our young mothers and young women, giving them unwavering faith and holy joy. Amen.',
                'icon_or_image_url' => '🌴',
            ],
            [
                'name' => 'St. Cyprian of Carthage',
                'slug' => 'st-cyprian-of-carthage',
                'title_designation' => 'Bishop, Martyr & African Church Father',
                'feast_day_month_day' => '09-16',
                'birth_year' => '200',
                'death_year' => '258',
                'country_region' => 'Carthage (Modern Tunisia), North Africa',
                'is_african_heritage' => true,
                'patronages' => ['North Africa', 'Bishops', 'Unity of the Church'],
                'biography' => 'A brilliant rhetorician who converted to Christianity in midlife, Cyprian became Bishop of Carthage. He organized heroic relief during the great plague of Carthage, wrote foundational treatises on the unity of the Catholic Church, and died a joyful martyr during the Valerian persecution.',
                'virtues_exemplified' => ['Love for the Church', 'Sacrificial Charity', 'Pastoral Leadership', 'Martyrdom'],
                'key_teachings_quotes' => [
                    'You cannot have God for your Father if you do not have the Church for your Mother.',
                    'Thanks be to God! (His final words upon hearing his death sentence for Christ).',
                ],
                'patronage_prayer' => 'St. Cyprian of Carthage, great African Bishop and Martyr, protect the unity of our Catholic Church and ignite a burning love for the Sacraments in our youth. Amen.',
                'icon_or_image_url' => '⛪',
            ],
            [
                'name' => 'St. Clement of Alexandria',
                'slug' => 'st-clement-of-alexandria',
                'title_designation' => 'Early African Theologian & Teacher of Wisdom',
                'feast_day_month_day' => '12-04',
                'birth_year' => '150',
                'death_year' => '215',
                'country_region' => 'Alexandria, Egypt, North Africa',
                'is_african_heritage' => true,
                'patronages' => ['Catechetical Teachers', 'Scholars', 'Philosophers', 'Egypt'],
                'biography' => 'Head of the legendary Catechetical School of Alexandria in Egypt, Clement united classical wisdom with the light of the Gospel, teaching that Jesus Christ is the divine Logos (Word) who educates human hearts into the full maturity of divine love.',
                'virtues_exemplified' => ['Integration of Faith and Reason', 'Teaching Diligence', 'Christian Humanism'],
                'key_teachings_quotes' => [
                    'Prayer is a conversation with God. Even if we whisper, we are heard.',
                    'Faith is the compass of the soul.',
                ],
                'patronage_prayer' => 'St. Clement of Alexandria, guide Catholic students and scholars in our Diocese to love learning and find the fullness of wisdom in Jesus Christ. Amen.',
                'icon_or_image_url' => '💡',
            ],

            // =========================================================================
            // 4. THE THREE HISTORIC AFRICAN POPES
            // =========================================================================
            [
                'name' => 'Pope St. Victor I',
                'slug' => 'pope-st-victor-i',
                'title_designation' => 'First African Pope & Martyr (14th Pope)',
                'feast_day_month_day' => '07-28',
                'birth_year' => '140',
                'death_year' => '199',
                'country_region' => 'Roman Africa (Modern Tunisia/Libya)',
                'is_african_heritage' => true,
                'patronages' => ['Popes', 'African Leadership', 'Liturgical Unity', 'Roman Africa'],
                'biography' => 'Born in North Africa, Victor I became the 14th Bishop of Rome (189–199 AD). He unified the universal calculation of Easter Sunday, introduced Latin as the official liturgical language of the Roman Church, and died a martyr under Emperor Septimius Severus.',
                'virtues_exemplified' => ['Papal Leadership', 'Liturgical Harmony', 'Doctrinal Fortitude', 'Martyrdom'],
                'key_teachings_quotes' => [
                    'The Church in all lands must celebrate the triumph of the Lord\'s Resurrection in one harmonious voice.',
                ],
                'patronage_prayer' => 'Pope St. Victor I, first African successor of St. Peter, pray for the Holy Father and all African Church leaders, that they may lead Christ\'s flock with courage and truth. Amen.',
                'icon_or_image_url' => '🗝️',
            ],
            [
                'name' => 'Pope St. Miltiades',
                'slug' => 'pope-st-miltiades',
                'title_designation' => 'African Pope of Peace & Edict of Milan (32nd Pope)',
                'feast_day_month_day' => '01-10',
                'birth_year' => '250',
                'death_year' => '314',
                'country_region' => 'North Africa',
                'is_african_heritage' => true,
                'patronages' => ['Religious Freedom', 'Peace Builders', 'African Popes'],
                'biography' => 'Born in North Africa, Miltiades served as the 32nd Pope (311–314 AD). He led the Church out of the bloody Diocletian persecutions, received the Lateran Palace as the first papal residence, and oversaw the historic Edict of Milan granting religious freedom to Christians.',
                'virtues_exemplified' => ['Reconciliation', 'Spiritual Resilience', 'Wisdom in Liberty', 'Firm Governance'],
                'key_teachings_quotes' => [
                    'After the storm of persecution, God has given peace to His Church. Let us walk worthy of this holy freedom.',
                ],
                'patronage_prayer' => 'Pope St. Miltiades, holy African Pope of peace, protect our nation of Zambia in peace and preserve the freedom of the Catholic Church to preach the Gospel. Amen.',
                'icon_or_image_url' => '🕊️',
            ],
            [
                'name' => 'Pope St. Gelasius I',
                'slug' => 'pope-st-gelasius-i',
                'title_designation' => 'African Pope of Charity & Biblical Canon (49th Pope)',
                'feast_day_month_day' => '11-21',
                'birth_year' => '410',
                'death_year' => '496',
                'country_region' => 'North Africa',
                'is_african_heritage' => true,
                'patronages' => ['The Poor', 'Biblical Scholars', 'Liturgists', 'African Popes'],
                'biography' => 'The third African Pope, Gelasius I was celebrated for his immense charity toward the poor, giving all papal revenues to famine relief. He formally defined the canon of Sacred Scripture (Decretum Gelasianum) and articulated the balance of spiritual and temporal authority.',
                'virtues_exemplified' => ['Love for the Impoverished', 'Theological Clarity', 'Biblical Stewardship', 'Sacramental Devotion'],
                'key_teachings_quotes' => [
                    'There are two powers by which this world is chiefly ruled: the sacred authority of the priesthood and the royal power.',
                    'Nothing is dearer to God than charity toward His poor.',
                ],
                'patronage_prayer' => 'Pope St. Gelasius I, African shepherd of the poor and defender of Sacred Scripture, ignite in our youth a passion to read the Word of God and serve the needy. Amen.',
                'icon_or_image_url' => '📜',
            ],

            // =========================================================================
            // 5. UNIVERSAL YOUTH PATRONS & HEROES OF PURITY
            // =========================================================================
            [
                'name' => 'St. Aloysius Gonzaga',
                'slug' => 'st-aloysius-gonzaga',
                'title_designation' => 'Universal Patron of Catholic Youth & Students',
                'feast_day_month_day' => '06-21',
                'birth_year' => '1568',
                'death_year' => '1591',
                'country_region' => 'Italy',
                'is_african_heritage' => false,
                'patronages' => ['Catholic Youth', 'Young Students', 'Plague Victims & Caregivers', 'Purity'],
                'biography' => 'Born into Italian royalty, Aloysius renounced his inheritance and princely title to enter the Society of Jesus (Jesuits). When a deadly plague struck Rome, he volunteered to carry infected patients to hospitals and bathe them, contracting the disease and dying joyfully at age 23.',
                'virtues_exemplified' => ['Heroic Charity', 'Chastity', 'Humility', 'Renunciation of Worldly Status'],
                'key_teachings_quotes' => [
                    'I am a piece of twisted iron, and have entered into religion to be straightened out.',
                    'He who does not conquer himself in small things will not conquer in great ones.',
                ],
                'patronage_prayer' => 'St. Aloysius Gonzaga, patron of youth and students, teach us to love purity, to serve the sick and suffering, and to value heavenly treasure above worldly power. Amen.',
                'icon_or_image_url' => '⚜️',
            ],
            [
                'name' => 'St. Dominic Savio',
                'slug' => 'st-dominic-savio',
                'title_designation' => 'Patron of Young Students & Altar Servers',
                'feast_day_month_day' => '05-06',
                'birth_year' => '1842',
                'death_year' => '1857',
                'country_region' => 'Italy',
                'is_african_heritage' => false,
                'patronages' => ['Choirboys', 'Altar Servers', 'Juvenile Delinquents', 'Young Students'],
                'biography' => 'A student of St. John Bosco at the Oratory of St. Francis de Sales in Turin, Dominic made his First Communion at age seven with the motto "Death rather than sin." He died of illness at just 14 years old, leaving a legacy of cheerful daily holiness and apostolic friendship among fellow boys.',
                'virtues_exemplified' => ['Everyday Holiness', 'Cheerfulness', 'Eucharistic Devotion', 'Peacemaking among Peers'],
                'key_teachings_quotes' => [
                    'Death rather than sin!',
                    'I am not capable of doing big things, but I want to do everything, even the smallest things, for the greater glory of God.',
                    'Here we make holiness consist in being always cheerful.',
                ],
                'patronage_prayer' => 'St. Dominic Savio, young saint of joy, help our children and teenagers to keep our First Communion promises and find true happiness in serving God. Amen.',
                'icon_or_image_url' => '🕊️',
            ],
            [
                'name' => 'St. Maria Goretti',
                'slug' => 'st-maria-goretti',
                'title_designation' => 'Virgin Martyr & Patroness of Teenage Youth',
                'feast_day_month_day' => '07-06',
                'birth_year' => '1890',
                'death_year' => '1902',
                'country_region' => 'Italy',
                'is_african_heritage' => false,
                'patronages' => ['Teenagers', 'Youth Purity', 'Victims of Assault', 'Forgiveness'],
                'biography' => 'An 11-year-old Italian farm girl, Maria Goretti resisted an assault by her neighbor Alessandro Serenelli, telling him "It is a sin; God forbids it!" Fatally stabbed fourteen times, she forgave her attacker on her deathbed, wishing him to be with her in Paradise. Alessandro later converted and attended her canonization.',
                'virtues_exemplified' => ['Radical Forgiveness', 'Moral Courage', 'Chastity unto Death', 'Mercy'],
                'key_teachings_quotes' => [
                    'I forgive Alessandro Serenelli with all my heart, and I want him to be with me in Heaven forever.',
                    'No, Alessandro, it is a sin; you will go to hell!',
                ],
                'patronage_prayer' => 'St. Maria Goretti, youthful martyr of purity and forgiveness, give our teenage boys and girls the courage to choose moral integrity and the grace to forgive those who hurt them. Amen.',
                'icon_or_image_url' => '🌸',
            ],
            [
                'name' => 'Blessed Carlo Acutis',
                'slug' => 'blessed-carlo-acutis',
                'title_designation' => 'Patron of Digital Youth & Internet Evangelization',
                'feast_day_month_day' => '10-12',
                'birth_year' => '1991',
                'death_year' => '2006',
                'country_region' => 'Italy & UK',
                'is_african_heritage' => false,
                'patronages' => ['Internet Users', 'Digital Missionaries', 'Millennial & Gen-Z Catholics', 'Computer Programmers'],
                'biography' => 'A modern teenager who loved gaming, programming, and football, Carlo Acutis went to daily Mass and created a global website cataloging Eucharistic Miracles across the centuries. Dying of leukemia at age 15, he offered his sufferings for Pope Benedict XVI and the Church.',
                'virtues_exemplified' => ['Eucharistic Centeredness', 'Digital Evangelization', 'Joyful Simplicity', 'Heroic Acceptance of Sickness'],
                'key_teachings_quotes' => [
                    'The Eucharist is my highway to Heaven.',
                    'All people are born as originals, but many die as photocopies.',
                    'To always be close to Jesus, that\'s my life plan.',
                ],
                'patronage_prayer' => 'Blessed Carlo Acutis, millennial friend of Jesus in the Blessed Sacrament, guide our youth to use social media, phones, and technology for the glory of God and the salvation of souls. Amen.',
                'icon_or_image_url' => '💻',
            ],
            [
                'name' => 'St. Tarcisius',
                'slug' => 'st-tarcisius',
                'title_designation' => 'Martyr of the Holy Eucharist & Altar Servers',
                'feast_day_month_day' => '08-15',
                'birth_year' => '245',
                'death_year' => '257',
                'country_region' => 'Rome, Italy',
                'is_african_heritage' => false,
                'patronages' => ['Altar Servers', 'First Communicants', 'Eucharistic Guardians'],
                'biography' => 'A young 12-year-old acolyte in early Christian Rome during the Valerian persecution, Tarcisius volunteered to carry the Blessed Sacrament secretly to imprisoned Christians awaiting execution. Confronted by a pagan mob who demanded he surrender the Holy Eucharist, he clasped Christ to his chest and was beaten to death, never letting the Sacred Host be profaned.',
                'virtues_exemplified' => ['Eucharistic Reverence', 'Sacrificial Bravery', 'Fidelity in Service'],
                'key_teachings_quotes' => [
                    'I will never betray my God to dogs!',
                ],
                'patronage_prayer' => 'St. Tarcisius, brave young martyr of the Holy Eucharist, instill in all altar servers and youth of our diocese deep reverence and adoration for Jesus in the Blessed Sacrament. Amen.',
                'icon_or_image_url' => '🥖',
            ],
            [
                'name' => 'St. Agnes of Rome',
                'slug' => 'st-agnes-of-rome',
                'title_designation' => 'Virgin Martyr & Patroness of Young Girls',
                'feast_day_month_day' => '01-21',
                'birth_year' => '291',
                'death_year' => '304',
                'country_region' => 'Rome, Italy',
                'is_african_heritage' => false,
                'patronages' => ['Young Girls', 'Children of Mary', 'Chastity', 'Betrothed Couples'],
                'biography' => 'A 13-year-old Christian girl in ancient Rome, Agnes refused wealthy suitors who sought her hand in marriage, stating that she was betrothed to Jesus Christ. Despite threats of torture, she went to her execution with joyful dignity, becoming one of the most venerated virgin martyrs in Church history.',
                'virtues_exemplified' => ['Single-hearted Devotion to Christ', 'Fearlessness', 'Purity of Soul'],
                'key_teachings_quotes' => [
                    'Christ is my spouse; He has chosen me first and His I will remain.',
                ],
                'patronage_prayer' => 'St. Agnes of Rome, pure and courageous witness for Christ, pray for our young Catholic girls and youth, keeping their hearts pure and devoted to Jesus. Amen.',
                'icon_or_image_url' => '🐑',
            ],
            [
                'name' => 'St. Joan of Arc',
                'slug' => 'st-joan-of-arc',
                'title_designation' => 'Teenage Heroine, Martyr & Patroness of Soldiers',
                'feast_day_month_day' => '05-30',
                'birth_year' => '1412',
                'death_year' => '1431',
                'country_region' => 'France',
                'is_african_heritage' => false,
                'patronages' => ['Soldiers', 'Courageous Youth', 'Prisoners', 'France'],
                'biography' => 'A 17-year-old illiterate peasant girl who received heavenly visions from St. Michael the Archangel and St. Catherine of Alexandria, Joan led French forces to liberate Orleans in obedience to God. Betrayed and condemned by a corrupt political court, she was burned at the stake at age 19, dying with her eyes fixed on a crucifix while calling upon the name of "Jesus."',
                'virtues_exemplified' => ['Heroic Obedience to God', 'Courage against All Odds', 'Faith in Adversity'],
                'key_teachings_quotes' => [
                    'I am not afraid; God is with me. I was born to do this!',
                    'Hold the cross high before my eyes so that I may see it through the flames!',
                ],
                'patronage_prayer' => 'St. Joan of Arc, brave young servant of God, inspire our Catholic youth to stand courageous against the pressures of the world and obey God\'s call in our lives. Amen.',
                'icon_or_image_url' => '⚔️',
            ],

            // =========================================================================
            // 6. UNIVERSAL DOCTORS OF THE CHURCH
            // =========================================================================
            [
                'name' => 'St. Thomas Aquinas',
                'slug' => 'st-thomas-aquinas',
                'title_designation' => 'Angelic Doctor & Universal Theologian',
                'feast_day_month_day' => '01-28',
                'birth_year' => '1225',
                'death_year' => '1274',
                'country_region' => 'Italy',
                'is_african_heritage' => false,
                'patronages' => ['Catholic Schools', 'Universities', 'Theologians', 'Students', 'Academics'],
                'biography' => 'Dominican friar, philosopher, and theologian, Thomas Aquinas authored the monumental "Summa Theologiae" harmonizing Aristotelian philosophy with Catholic revelation. He composed the immortal Eucharistic hymns "Tantum Ergo" and "Panis Angelicus." Pope St. Pius V declared him Doctor of the Church in 1567.',
                'virtues_exemplified' => ['Theological Genius', 'Eucharistic Adoration', 'Purity of Intellect', 'Humility'],
                'key_teachings_quotes' => [
                    'To one who has faith, no explanation is necessary. To one without faith, no explanation is possible.',
                    'Grant me, O Lord my God, a mind to know You, a heart to seek You, and wisdom to find You.',
                ],
                'patronage_prayer' => 'St. Thomas Aquinas, Angelic Doctor, enlighten the minds of our youth as we study the Catholic faith, that we may love God with all our mind and heart. Amen.',
                'icon_or_image_url' => '📚',
            ],
            [
                'name' => 'St. Catherine of Siena',
                'slug' => 'st-catherine-of-siena',
                'title_designation' => 'Doctor of the Church & Mystic of Unity',
                'feast_day_month_day' => '04-29',
                'birth_year' => '1347',
                'death_year' => '1380',
                'country_region' => 'Italy',
                'is_african_heritage' => false,
                'patronages' => ['Europe', 'Nurses', 'Papal Unity', 'Young Women Leaders'],
                'biography' => 'A Dominican tertiary who could neither read nor write until adulthood, Catherine dictated profound mystical treatises ("The Dialogue") and wrote courageous letters to popes, kings, and cardinals. She persuaded Pope Gregory XI to return the papacy from Avignon back to Rome, and was proclaimed Doctor of the Church in 1970.',
                'virtues_exemplified' => ['Zeal for Church Unity', 'Prophetic Courage', 'Mystical Love of Christ', 'Care for Plague Victims'],
                'key_teachings_quotes' => [
                    'Be who God meant you to be and you will set the world on fire!',
                    'All the way to Heaven is Heaven, because Jesus said, "I am the Way."',
                ],
                'patronage_prayer' => 'St. Catherine of Siena, Doctor of the Church, ignite in our young people the fire of the Holy Spirit to transform our society and serve the Church with boldness. Amen.',
                'icon_or_image_url' => '🔥',
            ],
            [
                'name' => 'St. Teresa of Ávila',
                'slug' => 'st-teresa-of-avila',
                'title_designation' => 'Doctor of Prayer & Reformer of Carmel',
                'feast_day_month_day' => '10-15',
                'birth_year' => '1515',
                'death_year' => '1582',
                'country_region' => 'Spain',
                'is_african_heritage' => false,
                'patronages' => ['Contemplatives', 'People in Need of Grace', 'Spain'],
                'biography' => 'Reformer of the Discalced Carmelite Order and author of spiritual masterpieces including "The Interior Castle" and "The Way of Perfection," Teresa mapped the journey of the soul from vocal prayer to profound mystical union with God. She was the first woman declared a Doctor of the Church.',
                'virtues_exemplified' => ['Interior Prayer', 'Spiritual Fortitude', 'Reforming Zeal', 'Holy Friendship with Christ'],
                'key_teachings_quotes' => [
                    'Let nothing disturb you, let nothing frighten you. All things are passing; God never changes. Patience obtains all things. Whoever has God lacks nothing; God alone suffices.',
                    'Mental prayer is nothing other than an intimate sharing between friends; it means taking time frequently to be alone with Him who we know loves us.',
                ],
                'patronage_prayer' => 'St. Teresa of Ávila, teacher of prayer, teach our Catholic youth how to pray from the heart and rest in God\'s loving presence. Amen.',
                'icon_or_image_url' => '🏰',
            ],
            [
                'name' => 'St. John Chrysostom',
                'slug' => 'st-john-chrysostom',
                'title_designation' => 'Doctor of the Church & Golden-Mouthed Preacher',
                'feast_day_month_day' => '09-13',
                'birth_year' => '349',
                'death_year' => '407',
                'country_region' => 'Antioch & Constantinople',
                'is_african_heritage' => false,
                'patronages' => ['Preachers', 'Orators', 'Public Speakers', 'Epilepsy'],
                'biography' => 'Patriarch of Constantinople, John earned the surname "Chrysostom" (Golden-Mouthed) for his eloquent, fiery biblical preaching defending the poor and rebuking imperial corruption. He composed the Divine Liturgy of St. John Chrysostom and suffered exile for Christ.',
                'virtues_exemplified' => ['Courageous Preaching', 'Defense of the Poor', 'Love for Sacred Liturgy'],
                'key_teachings_quotes' => [
                    'If you cannot find Christ in the beggar at the church door, you will not find Him in the chalice.',
                    'Glory be to God for all things!',
                ],
                'patronage_prayer' => 'St. John Chrysostom, Doctor of divine liturgy, inspire our youth with a deep love for the Holy Mass and generosity to the poor. Amen.',
                'icon_or_image_url' => '🗣️',
            ],
            [
                'name' => 'St. Jerome',
                'slug' => 'st-jerome',
                'title_designation' => 'Doctor of Sacred Scripture & Translator of the Vulgate',
                'feast_day_month_day' => '09-30',
                'birth_year' => '347',
                'death_year' => '420',
                'country_region' => 'Dalmatia & Bethlehem',
                'is_african_heritage' => false,
                'patronages' => ['Biblical Scholars', 'Translators', 'Librarians', 'Students'],
                'biography' => 'Living as an ascetic hermit in a cave in Bethlehem beside the birthplace of Jesus, Jerome spent thirty years translating the Old and New Testaments from Hebrew and Greek into Latin (The Vulgate), giving the Catholic Church her authoritative scriptural text.',
                'virtues_exemplified' => ['Biblical Scholarship', 'Ascetic Discipline', 'Zeal for the Word of God'],
                'key_teachings_quotes' => [
                    'Ignorance of Scripture is ignorance of Christ.',
                    'Read assiduously and learn as much as you can. Let sleep find you on your feet with a holy book in your hand.',
                ],
                'patronage_prayer' => 'St. Jerome, Doctor of Scripture, open the minds of our youth to understand the Bible and fall in love with Jesus Christ in the pages of Holy Scripture. Amen.',
                'icon_or_image_url' => '📖',
            ],
            [
                'name' => 'St. Francis de Sales',
                'slug' => 'st-francis-de-sales',
                'title_designation' => 'Doctor of Divine Love & Everyday Holiness',
                'feast_day_month_day' => '01-24',
                'birth_year' => '1567',
                'death_year' => '1622',
                'country_region' => 'France & Switzerland',
                'is_african_heritage' => false,
                'patronages' => ['Catholic Writers', 'Journalists', 'Deaf People', 'Spiritual Directors'],
                'biography' => 'Bishop of Geneva, Francis de Sales authored "Introduction to the Devout Life," proving that genuine holiness is possible and joyful for laypeople in every walk of life—soldiers, workers, students, and married couples—through gentleness and patient love.',
                'virtues_exemplified' => ['Gentleness', 'Everyday Devotion', 'Patience', 'Spiritual Guidance'],
                'key_teachings_quotes' => [
                    'A spoonful of honey attracts more flies than a barrel of vinegar.',
                    'Be who you are and be that well, so that you may bring honor to the Master Craftsman whose handiwork you are.',
                    'Never be in a hurry; do everything quietly and in a calm spirit.',
                ],
                'patronage_prayer' => 'St. Francis de Sales, gentle Doctor of holiness, guide our youth to live devout, kind, and peaceful Catholic lives in our daily routines. Amen.',
                'icon_or_image_url' => '🍯',
            ],

            // =========================================================================
            // 7. UNIVERSAL EARLY MARTYRS
            // =========================================================================
            [
                'name' => 'St. Stephen Protomartyr',
                'slug' => 'st-stephen',
                'title_designation' => 'First Christian Martyr & Deacon',
                'feast_day_month_day' => '12-26',
                'birth_year' => '5',
                'death_year' => '34',
                'country_region' => 'Jerusalem',
                'is_african_heritage' => false,
                'patronages' => ['Deacons', 'Altar Servers', 'Headache Sufferers', 'Stonemasons'],
                'biography' => 'One of the seven original deacons ordained by the Apostles in Jerusalem, Stephen was filled with the Holy Spirit and wisdom. Hauled before the Sanhedrin for preaching the Risen Jesus, he looked up into Heaven and saw the glory of God. While being stoned to death, he prayed for his killers, among whom was young Saul of Tarsus.',
                'virtues_exemplified' => ['Forgiveness of Persecutors', 'Apostolic Boldness', 'Diaconal Service', 'Vision of Faith'],
                'key_teachings_quotes' => [
                    'Lord, do not hold this sin against them!',
                    'Behold, I see the heavens opened and the Son of Man standing at the right hand of God.',
                ],
                'patronage_prayer' => 'St. Stephen Protomartyr, you were the first to shed blood for Christ. Pray for all Catholic youth when they are mocked or opposed for standing up for the Gospel. Amen.',
                'icon_or_image_url' => '💎',
            ],
            [
                'name' => 'St. Lawrence of Rome',
                'slug' => 'st-lawrence',
                'title_designation' => 'Deacon & Martyr of Rome',
                'feast_day_month_day' => '08-10',
                'birth_year' => '225',
                'death_year' => '258',
                'country_region' => 'Rome, Italy & Spain',
                'is_african_heritage' => false,
                'patronages' => ['Deacons', 'The Poor', 'Cooks', 'Comedians', 'Altar Servers'],
                'biography' => 'Deacon of the Church in Rome, Lawrence was commanded by the Roman Prefect to surrender the treasures of the Church. Lawrence gathered the blind, the lame, the orphans, and the widows, presenting them to the Prefect: "Behold, these are the treasures of the Church!" He was martyred on a gridiron with joyful courage.',
                'virtues_exemplified' => ['Love for the Impoverished', 'Holy Humor in Suffering', 'Diaconal Fidelity'],
                'key_teachings_quotes' => [
                    'The Church is truly rich, far richer than your emperor. The poor are the Church\'s greatest treasures.',
                    'Turn me over; I\'m done on this side!',
                ],
                'patronage_prayer' => 'St. Lawrence, heroic deacon and martyr, teach our youth to see Christ in the poor, the sick, and the needy of our parishes. Amen.',
                'icon_or_image_url' => '🔥',
            ],
        ];

        foreach ($saints as $saintData) {
            SaintProfile::updateOrCreate(
                ['slug' => $saintData['slug']],
                $saintData
            );
        }
    }
}
